name: CI
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  tests:
    uses: "SciML/.github/.github/workflows/grouped-tests.yml@refs/pull/137/head"
    with:
      # Temporary until SciML/.github retags v1 with #136/#137
      dotgithub-ref: master
    secrets: "inherit"
