name: Documentation
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  docs:
    name: "Documentation"
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    with:
      coverage: true
    secrets: "inherit"
