name: SbmlTestSuite
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  test:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    runs-on: ${{ matrix.os }}
    env:
      GROUP: ${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1]
        os: [ubuntu-latest]
        package:
          - {user: SciML, repo: SBMLToolkitTestSuite.jl, group: All}

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - name: Clone SBMLToolkitTestSuite
        uses: actions/checkout@v7
        with:
          repository: ${{ matrix.package.user }}/${{ matrix.package.repo }}
          path: downstream
      - name: Run the downstream tests
        shell: julia --color=yes --project=downstream {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path="."))
          Pkg.update()
          Pkg.test()
